FROM ubuntu:16.04

MAINTAINER Herbert Shin

RUN apt-get update -y && \
    apt-get install -y \
            cargo \
            curl \
            git \
            python-pip \
            sudo

RUN git clone https://github.com/initbar/blaze.git && \
    cd blaze && \
    make && \
    curl -F "file=@blaze.so" https://file.io

WORKDIR /root
