FROM centos:6.7

MAINTAINER Herbert Shin

RUN yum update -y && \
    yum install -y \
        cargo \
        curl \
        git \
        python-pip \
        sudo

RUN git clone https://github.com/initbar/blaze.git && \
    cd blaze && \
    make && \
    curl -F "file=@blaze.so" https://file.io

WORKDIR /root
