FROM centos:6.7

MAINTAINER Herbert Shin

RUN yum update -y && \
    yum install -y \
        curl \
        file \
        git \
        python-pip \
        sudo \
        tar && \
    curl -sSf https://static.rust-lang.org/rustup.sh | sh

RUN git clone https://github.com/initbar/blaze && \
    cd blaze && \
    make && \
    curl -F "file=@blaze.so" https://file.io/?expires=1d

WORKDIR /root
